
package fr.polyschool;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "monServiceTest", targetNamespace = "www.polyschool.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MonServiceTest {


    /**
     * 
     * @param svt
     * @param pc
     * @param math
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "average", targetNamespace = "www.polyschool.fr", className = "fr.polyschool.Average")
    @ResponseWrapper(localName = "averageResponse", targetNamespace = "www.polyschool.fr", className = "fr.polyschool.AverageResponse")
    @Action(input = "www.polyschool.fr/monServiceTest/averageRequest", output = "www.polyschool.fr/monServiceTest/averageResponse")
    public double average(
        @WebParam(name = "math", targetNamespace = "")
        double math,
        @WebParam(name = "Pc", targetNamespace = "")
        double pc,
        @WebParam(name = "SVT", targetNamespace = "")
        double svt);

}
